version: '3'

services:
  app:
    build: .
    container_name: webpack-practice
    ports:
      - '8080:8080'
    working_dir: /src
    volumes:
      - ./:/src
    # docker run -iを意味する
    stdin_open: true
    # -tを意味する
    tty: true